import numpy as np
import matplotlib.pyplot as plt
import os
import numpy as np
import pandas as pd
from PIL import Image, ImageDraw
import cv2
import json
import shutil
from typing import List, Tuple, Dict, Any
import math
from pathlib import Path
######## Global Constants ########
Total_sequence_length = 20
total_sequence_time = 8


class Aggregator():
    def __init__(self, data_path: str, output_path: str = "sdd_fusion_output"):
        """
        Initialize the aggregator with data path and output path.
        
        Args:
            data_path (str): Path to the input data.
            output_path (str): Path to save the aggregated results.
        """
        self.data_path = data_path
        self.output_path = output_path
        self.maps = {}

    def load_data(self):
        """
        Load the data from the specified path.
        This method should be implemented to read the actual data files.
        """
        # Placeholder for loading data logic
        # For example, you might load numpy arrays or other formats here
        pass
    def aggregate_data(self):
        """
        Aggregate the loaded data.
        This method should be implemented to perform the actual aggregation logic.
        """
        # Placeholder for aggregation logic
        # For example, you might combine multiple data sources or perform statistical analysis
        pass



class GlobalHeatmapGenerator:
    def __init__(self, drone_data_path: str, original_dataset_path: str, output_path: str = "global_heatmap_data"):
        """
        Initialize the global heatmap generator using existing drone data
        
        Args:
            drone_data_path: Path to the existing drone data (generated by second code)
            original_dataset_path: Path to the original Stanford drone dataset
            output_path: Path where the global heatmap data will be created
        """
        self.drone_data_path = Path(drone_data_path)
        self.original_dataset_path = Path(original_dataset_path)
        self.output_path = Path(output_path)
        
        # Label to number mapping
        self.label_mapping = {
            'Pedestrian': 1,
            'Biker': 2,
            'Skater': 3,
            'Cart': 4,
            'Car': 5,
            'Bus': 6,
            'Person': 1,  # Same as Pedestrian
            'Bike': 2,    # Same as Biker
            'Default': 9
        }
        
    def _get_locations(self) -> List[str]:
        """Get all available locations from the drone data"""
        locations = []
        
        if self.drone_data_path.exists():
            for item in self.drone_data_path.iterdir():
                if item.is_dir():
                    locations.append(item.name)
        
        return locations
    
    def _get_drone_ids(self, location: str) -> List[str]:
        """Get all drone IDs for a location"""
        drone_ids = []
        location_path = self.drone_data_path / location
        
        if location_path.exists():
            for item in location_path.iterdir():
                if item.is_dir() and item.name.startswith('drone'):
                    drone_ids.append(item.name)
        
        return sorted(drone_ids)
    
    def _get_videos_for_location(self, location: str) -> List[str]:
        """Get all video names for a location by checking first drone"""
        drone_ids = self._get_drone_ids(location)
        if not drone_ids:
            return []
        
        first_drone_path = self.drone_data_path / location / drone_ids[0]
        videos = []
        
        for file in first_drone_path.glob("*_annotations.txt"):
            video_name = file.stem.replace("_annotations", "")
            videos.append(video_name)
        
        return videos
    
    def _load_drone_annotations(self, location: str, drone_id: str, video: str) -> pd.DataFrame:
        """
        Load annotations for a specific drone
        
        Args:
            location: Location name
            drone_id: Drone identifier
            video: Video name
            
        Returns:
            DataFrame with drone annotations
        """
        annotation_file = self.drone_data_path / location / drone_id / f"{video}_annotations.txt"
        
        if not annotation_file.exists():
            return pd.DataFrame()
        
        try:
            # Load local annotations
            df = pd.read_csv(annotation_file, sep='\s+', header=None,
                           names=['trackId', 'local_xmin', 'local_ymin', 'local_xmax', 'local_ymax',
                                 'frame', 'lost', 'occluded', 'generated', 'label'])
            return df
        except Exception as e:
            print(f"Error loading annotations for {drone_id} in {video}: {e}")
            return pd.DataFrame()
    
    def _load_drone_metadata(self, location: str, drone_id: str, video: str) -> Dict:
        """Load metadata for a specific drone"""
        metadata_file = self.drone_data_path / location / drone_id / f"{video}_metadata.json"
        
        if not metadata_file.exists():
            return {}
        
        try:
            with open(metadata_file, 'r') as f:
                return json.load(f)
        except Exception as e:
            print(f"Error loading metadata for {drone_id} in {video}: {e}")
            return {}
    
    def _get_drone_position_from_fov(self, location: str, drone_id: str, video: str) -> Tuple[float, float]:
        """
        Estimate drone position from FOV image and reference image
        This is a simplified approach - in practice you'd need the actual positions
        """
        # For now, we'll use a placeholder approach
        # In a real implementation, you'd need to store or calculate the actual drone positions
        
        # Load metadata to get any stored position info
        metadata = self._load_drone_metadata(location, drone_id, video)
        
        # Extract drone number for positioning (this is a simplified approach)
        drone_num = int(drone_id.replace('drone', ''))
        return (metadata.get('x_position', 0), metadata.get('y_position', 0))  # Default to (0, 0) if not found

        # Load reference image to get dimensions
        # ref_image = self._load_reference_image(location, video)
        # if ref_image is None:
        #     return (0, 0)
        
        # height, width = ref_image.shape[:2]
        
        # # Simple grid positioning based on drone number (you should replace this with actual positions)
        # positions = {
        #     1: (width * 0.25, height * 0.25),
        #     2: (width * 0.75, height * 0.25),
        #     3: (width * 0.25, height * 0.75),
        #     4: (width * 0.75, height * 0.75),
        #     5: (width * 0.5, height * 0.5),
        # }
        
        # return positions.get(drone_num, (width * 0.5, height * 0.5))
    
    def _load_reference_image(self, location: str, video: str) -> np.ndarray:
        """Load reference image from original dataset"""
        ref_path = self.original_dataset_path / "annotations" / location / video / "reference.jpg"
        if ref_path.exists():
            return cv2.imread(str(ref_path))
        return None
    
    def _convert_local_to_global_coordinates(self, local_annotations: pd.DataFrame, 
                                           drone_pos: Tuple[float, float]) -> pd.DataFrame:
        """
        Convert local drone coordinates back to global coordinates
        
        Args:
            local_annotations: Annotations in local coordinates
            drone_pos: (x, y) position of the drone
            
        Returns:
            Annotations in global coordinates
        """
        if local_annotations.empty:
            return local_annotations
        
        global_annotations = local_annotations.copy()
        
        # Convert local coordinates back to global
        global_annotations['xmin'] = local_annotations['local_xmin'] + drone_pos[0]
        global_annotations['ymin'] = local_annotations['local_ymin'] + drone_pos[1]
        global_annotations['xmax'] = local_annotations['local_xmax'] + drone_pos[0]
        global_annotations['ymax'] = local_annotations['local_ymax'] + drone_pos[1]
        
        # Calculate global center points
        global_annotations['center_x'] = (global_annotations['xmin'] + global_annotations['xmax']) / 2
        global_annotations['center_y'] = (global_annotations['ymin'] + global_annotations['ymax']) / 2
        
        return global_annotations
    
    def _combine_all_drone_data(self, location: str, video: str) -> pd.DataFrame:
        """
        Combine annotations from all drones for a location/video
        
        Args:
            location: Location name
            video: Video name
            
        Returns:
            Combined annotations DataFrame
        """
        drone_ids = self._get_drone_ids(location)
        all_annotations = pd.DataFrame()
        
        for drone_id in drone_ids:
            # Load drone annotations
            local_annotations = self._load_drone_annotations(location, drone_id, video)
            
            if local_annotations.empty:
                continue
            
            # Get drone position
            drone_pos = self._get_drone_position_from_fov(location, drone_id, video)
            
            # Convert to global coordinates
            global_annotations = self._convert_local_to_global_coordinates(local_annotations, drone_pos)
            
            # Add drone ID
            global_annotations['drone_id'] = drone_id
            
            # Combine with other drones
            all_annotations = pd.concat([all_annotations, global_annotations], ignore_index=True)
        
        # Remove duplicates (same track might be seen by multiple drones)
        if not all_annotations.empty:
            all_annotations = all_annotations.drop_duplicates(
                subset=['trackId', 'frame'], keep='first')
        
        return all_annotations
    
    def _generate_global_heatmap_sequences(self, location: str, video: str,
                                         combined_annotations: pd.DataFrame, 
                                         reference_image: np.ndarray) -> List[np.ndarray]:
        """
        Generate global heatmap sequences combining all drone data
        
        Args:
            location: Location name
            video: Video name
            combined_annotations: Combined annotations from all drones
            reference_image: Reference image for the scene
            
        Returns:
            List of global heatmap sequences
        """
        if combined_annotations.empty or reference_image is None:
            return []
        
        # Convert reference image to grayscale
        if len(reference_image.shape) == 3:
            reference_gray = cv2.cvtColor(reference_image, cv2.COLOR_BGR2GRAY)
        else:
            reference_gray = reference_image.copy()
        
        # Get frame range
        min_frame = combined_annotations['frame'].min()
        max_frame = combined_annotations['frame'].max()
        
        # Create sequences: 8 seconds = 20 frames, overlap = 4 seconds = 10 frames
        sequence_length = 20  # 8 seconds at 2.5 Hz
        overlap = 10  # 4 seconds at 2.5 Hz
        step = sequence_length - overlap  # 10 frames
        
        sequences = []
        
        for start_frame in range(min_frame, max_frame - sequence_length + 1, step):
            end_frame = start_frame + sequence_length
            
            # Get annotations for this sequence
            sequence_annotations = combined_annotations[
                (combined_annotations['frame'] >= start_frame) & 
                (combined_annotations['frame'] < end_frame)
            ]
            
            if sequence_annotations.empty:
                continue
            
            # Create global heatmap for this sequence
            heatmap = self._create_global_sequence_heatmap(
                sequence_annotations, reference_gray)
            
            if heatmap is not None:
                sequences.append(heatmap)
        
        return sequences
    
    def _create_global_sequence_heatmap(self, sequence_annotations: pd.DataFrame, 
                                       reference_gray: np.ndarray) -> np.ndarray:
        """
        Create a global heatmap for a sequence on the reference image
        
        Args:
            sequence_annotations: Annotations for the sequence
            reference_gray: Grayscale reference image
            
        Returns:
            3D array with grayscale background and [id, label] tracks
        """
        if sequence_annotations.empty:
            return None
        
        height, width = reference_gray.shape
        
        # Create 3-channel output: [grayscale, id, label]
        heatmap = np.zeros((height, width, 3), dtype=np.int32)
        
        # Set grayscale background
        heatmap[:, :, 0] = reference_gray.astype(np.int32)
        
        # Add object tracks
        for _, row in sequence_annotations.iterrows():
            # Use global coordinates (center of bounding box)
            x = int(row['center_x'])
            y = int(row['center_y'])
            
            # Ensure coordinates are within bounds
            if 0 <= x < width and 0 <= y < height:
                track_id = int(row['trackId'])
                label = row['label'].strip('"')  # Remove quotes if present
                label_num = self.label_mapping.get(label, self.label_mapping['Default'])
                
                # Set [id, label] at this position
                heatmap[y, x, 1] = track_id
                heatmap[y, x, 2] = label_num
        
        return heatmap
    
    def _save_global_heatmap_sequences(self, sequences: List[np.ndarray], 
                                     location: str, video: str):
        """
        Save global heatmap sequences to files
        
        Args:
            sequences: List of global heatmap arrays
            location: Location name
            video: Video name
        """
        if not sequences:
            return
        
        # Create global heatmap directory
        global_heatmap_dir = self.output_path / location / "global_heatmaps"
        global_heatmap_dir.mkdir(parents=True, exist_ok=True)
        
        # Save each sequence
        for seq_idx, heatmap in enumerate(sequences):
            # Save as .npy file for easy loading
            heatmap_file = global_heatmap_dir / f"{video}_global_sequence_{seq_idx:03d}.npy"
            np.save(heatmap_file, heatmap)
            
            # Save visual representation (grayscale with colored tracks)
            visual_file = global_heatmap_dir / f"{video}_global_sequence_{seq_idx:03d}_visual.jpg"
            self._save_visual_heatmap(heatmap, visual_file)
            
            # Save metadata
            metadata = {
                'sequence_index': seq_idx,
                'video': video,
                'location': location,
                'shape': heatmap.shape,
                'data_format': '[grayscale, id, label]',
                'label_mapping': self.label_mapping,
                'channel_0': 'grayscale_background',
                'channel_1': 'track_id',
                'channel_2': 'label_number'
            }
            
            metadata_file = global_heatmap_dir / f"{video}_global_sequence_{seq_idx:03d}_metadata.json"
            with open(metadata_file, 'w') as f:
                json.dump(metadata, f, indent=2)
    
    def _save_visual_heatmap(self, heatmap: np.ndarray, output_file: Path):
        """
        Save a visual representation of the heatmap
        
        Args:
            heatmap: 3D heatmap array [grayscale, id, label]
            output_file: Output file path
        """
        # Create visualization
        visual = heatmap[:, :, 0].astype(np.uint8)  # Start with grayscale
        
        # Create colored overlay for tracks
        colored_overlay = np.zeros((*visual.shape, 3), dtype=np.uint8)
        
        # Define colors for different labels
        label_colors = {
            1: (255, 107, 107),  # Pedestrian - Red
            2: (78, 205, 196),   # Biker - Teal
            3: (69, 183, 209),   # Skater - Blue
            4: (150, 206, 180),  # Cart - Green
            5: (254, 202, 87),   # Car - Yellow
            6: (255, 159, 243),  # Bus - Pink
            9: (221, 160, 221)   # Default - Plum
        }
        
        # Add colored tracks
        for label_num, color in label_colors.items():
            mask = heatmap[:, :, 2] == label_num
            colored_overlay[mask] = color
        
        # Blend grayscale background with colored tracks
        track_mask = heatmap[:, :, 1] > 0  # Where there are tracks
        
        # Convert grayscale to 3-channel
        visual_3ch = cv2.cvtColor(visual, cv2.COLOR_GRAY2BGR)
        
        # Add colored tracks on top
        visual_3ch[track_mask] = colored_overlay[track_mask]
        
        # Save the visual
        cv2.imwrite(str(output_file), visual_3ch)
    
    def generate_global_heatmaps(self):
        """
        Generate global heatmaps from existing drone data
        """
        # Create output directory
        self.output_path.mkdir(parents=True, exist_ok=True)
        
        # Get all locations
        locations = self._get_locations()
        
        if not locations:
            print("No locations found in drone data")
            return
        
        for location in locations:
            print(f"Processing location: {location}")
            
            # Get all videos for this location
            videos = self._get_videos_for_location(location)
            
            if not videos:
                print(f"No videos found for location: {location}")
                continue
            
            # Process each video
            for video in videos:
                print(f"  Processing video: {video}")
                
                # Load reference image
                reference_image = self._load_reference_image(location, video)
                
                if reference_image is None:
                    print(f"    No reference image found for {video}")
                    continue
                
                # Combine all drone data for this video
                combined_annotations = self._combine_all_drone_data(location, video)
                
                if combined_annotations.empty:
                    print(f"    No annotations found for {video}")
                    continue
                
                # Generate global heatmap sequences
                global_sequences = self._generate_global_heatmap_sequences(
                    location, video, combined_annotations, reference_image)
                
                # Save global heatmap sequences
                self._save_global_heatmap_sequences(global_sequences, location, video)
                
                print(f"    Generated {len(global_sequences)} global heatmap sequences")
        
        print("Global heatmap generation completed!")
        print(f"Output saved to: {self.output_path}")
        print(f"Label mapping: {self.label_mapping}")

# Usage example:
if __name__ == "__main__":
    # Initialize the generator
    generator = GlobalHeatmapGenerator(
        drone_data_path="square_stanford_data",  # Path to existing drone data
        original_dataset_path="stanford_campus_dataset",  # Path to original Stanford dataset
        output_path="global_heatmap_data"  # Where to save global heatmaps
    )
    
    # Generate global heatmaps
    generator.generate_global_heatmaps()