# import torch
# import torch.nn as nn
import numpy as np
import math
import cv2

img = cv2.imread("stanford_data/archive/annotations/bookstore/video0/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/bookstore/video1/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/bookstore/video2/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/bookstore/video3/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/bookstore/video4/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/bookstore/video5/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/bookstore/video6/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/coupa/video0/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/coupa/video1/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/coupa/video2/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/coupa/video3/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/deathCircle/video0/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/deathCircle/video1/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/deathCircle/video2/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/deathCircle/video3/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/deathCircle/video4/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/gates/video0/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/gates/video1/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/gates/video2/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/gates/video3/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/gates/video4/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/gates/video5/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/gates/video6/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/gates/video7/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])

img = cv2.imread("stanford_data/archive/annotations/gates/video8/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video0/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video1/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video2/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video3/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video4/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video5/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video6/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])

img = cv2.imread("stanford_data/archive/annotations/hyang/video7/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video8/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video9/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video10/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video11/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video12/reference.jpg")
print(img.shape[0]/img.shape[1])
print(img.shape)
img = cv2.imread("stanford_data/archive/annotations/hyang/video13/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/hyang/video14/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/little/video0/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/little/video1/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/little/video2/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/little/video3/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
# img = cv2.imread("stanford_data/archive/annotations/little/video4/reference.jpg")
# print(img.shape)
img = cv2.imread("stanford_data/archive/annotations/nexus/video0/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video1/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video2/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video3/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video4/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video5/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video6/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video7/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video8/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video9/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video10/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/nexus/video11/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/quad/video0/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/quad/video1/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/quad/video2/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])
img = cv2.imread("stanford_data/archive/annotations/quad/video3/reference.jpg")
print(img.shape)
print(img.shape[0]/img.shape[1])

#         div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
#         pe[:, 0::2] = torch.sin(position * div_term)
#         pe[:, 1::2] = torch.cos(position * div_term)
#         pe = pe.unsqueeze(0)
#         self.register_buffer('pe', pe)

#     def forward(self, x):
#         return x + self.pe[:, :x.size(1), :]

# class LocalEncoder(nn.Module):
#     def __init__(self, input_dim, hidden_dim, output_dim):
#         super(LocalEncoder, self).__init__()
#         self.d_model = hidden_dim
#         self.embedding = nn.Linear(input_dim, self.d_model)
#         self.positional_encoding = PositionalEncoding(self.d_model)
#         self.encoder_layer = nn.TransformerEncoderLayer(d_model=self.d_model, nhead=8, dim_feedforward=self.d_model * 4)
#         self.transformer_encoder = nn.TransformerEncoder(self.encoder_layer, num_layers=1)

#     def forward(self, x):
#         # x shape: (batch_size, seq_len, input_dim)
#         batch_size, seq_len, _ = x.size()
        
#         # Linear embedding
#         x = self.embedding(x)
#         x = self.positional_encoding(x)
#         x = x.permute(1, 0, 2)
#         return self.transformer_encoder(x).permute(1, 0, 2)

# class SimpleViT(nn.Module):
#     def __init__(self, image_size=224, patch_size=16, in_channels=3, d_model=768, num_layers=12, num_heads=12, num_classes=1000):
#         super().__init__()
#         assert image_size % patch_size == 0
#         self.num_patches = (image_size // patch_size) ** 2
#         self.patch_dim = in_channels * patch_size * patch_size

#         self.patch_embed = nn.Linear(self.patch_dim, d_model)
#         self.cls_token = nn.Parameter(torch.randn(1, 1, d_model))
#         self.pos_embed = nn.Parameter(torch.randn(1, self.num_patches + 1, d_model))

#         encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=num_heads)
#         self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

#         self.mlp_head = nn.Sequential(
#             nn.LayerNorm(d_model),
#             nn.Linear(d_model, num_classes)
#         )

#     def forward(self, x):
#         B, C, H, W = x.shape
#         patch_size = int((self.patch_dim // C) ** 0.5)
#         x = x.unfold(2, patch_size, patch_size).unfold(3, patch_size, patch_size)  # (B, C, H/P, W/P, P, P)
#         x = x.contiguous().view(B, C, -1, patch_size, patch_size)
#         x = x.permute(0, 2, 1, 3, 4).flatten(2)  # (B, N, patch_dim)

#         x = self.patch_embed(x)  # (B, N, d_model)
#         cls_tokens = self.cls_token.expand(B, -1, -1)
#         x = torch.cat([cls_tokens, x], dim=1)
#         x += self.pos_embed

#         x = self.transformer(x)
#         cls_out = x[:, 0]
#         return self.mlp_head(cls_out)
    
    
